# Generated by Django 5.2.2 on 2025-06-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
